force-app/main/default/objects/Order/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment upon pickup</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Paypal</fullName>
            </value>
            <value>
                <fullName>Blik</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Producer__c.field-meta.xml
<CustomField>
    <fullName>Producer__c</fullName>
    <label>Producer</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>Intel</fullName>
            </value>
            <value>
                <fullName>Asus</fullName>
            </value>
            <value>
                <fullName>Acer</fullName>
            </value>
            <value>
                <fullName>Seagate</fullName>
            </value>
            <value>
                <fullName>Silentium</fullName>
            </value>
            <value>
                <fullName>Nvidia</fullName>
            </value>
            <value>
                <fullName>Sony</fullName>
            </value>
            <value>
                <fullName>HP</fullName>
            </value>
            <value>
                <fullName>A4Tech</fullName>
            </value>
            <value>
                <fullName>Adata</fullName>
            </value>
            <value>
                <fullName>Xiaomi</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>BenQ</fullName>
            </value>
            <value>
                <fullName>Dell</fullName>
            </value>
            <value>
                <fullName>MSI</fullName>
            </value>
            <value>
                <fullName>Biostar</fullName>
            </value>
            <value>
                <fullName>ASRock</fullName>
            </value>
            <value>
                <fullName>Philips</fullName>
            </value>
            <value>
                <fullName>Lenovo</fullName>
            </value>
            <value>
                <fullName>Cisco</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MS_ShoppingCartControllerTest.cls
@IsTest
public with sharing class MS_ShoppingCartControllerTest {

    @TestSetup
    public static void testSetup() {
        Pricebook2 standartPricebook = new Pricebook2(Id=Test.getStandardPricebookId(), IsActive=true);
        update  standartPricebook;
        Product2 productTest = new Product2(Name='CPU i5',Model__c='i5-4434',Producer__c='Intel',ProductCode='G88E',Available__c=true,Family='CPU',IsActive=true);
        insert productTest;
        PricebookEntry standartPrice = new PricebookEntry(UnitPrice=1000,Product2Id=productTest.Id, Pricebook2Id=standartPricebook.Id, IsActive=true);
        insert standartPrice;

        Account ac = new Account(Name='GoogleAuth');
        insert ac;

        Order order = new Order();
        order.Name = 'Test Order';
        order.Status = 'Draft';
        order.EffectiveDate = system.today();
        order.EndDate = system.today() + 4;
        order.AccountId = ac.Id;
        order.PaymentMethod__c = 'Blik';
        order.Pricebook2Id =  standartPricebook.Id ;
        insert order;

        OrderItem item = new OrderItem();
        item.OrderId = order.Id;
        item.Quantity = 1;
        item.UnitPrice = 1000;
        item.Product2id = productTest.Id;
        item.PricebookEntryId = standartPrice.Id;
        insert item;

    }

    @IsTest
    public static void shouldCreateContract(){
        Id contractID = MS_ShoppingCartController.createContract();
        List<Contract> contractList = [SELECT Id, ContractTerm FROM Contract WHERE Id = :contractID];
        System.assertEquals(12,contractList[0].ContractTerm);
    }

    @IsTest
    public static void shouldGetStandardProductPrice(){
        Product2 product = [SELECT Id FROM Product2 WHERE ProductCode='G88E'] ;
        PricebookEntry entry = MS_ShoppingCartController.getProductPrice(product.Id);
        System.assertEquals(1000,entry.UnitPrice);
    }

    @IsTest
    public static void shouldGetProductDetails(){
        Product2 product = [SELECT Id, Name FROM Product2 WHERE ProductCode='G88E'];
        List<Product2> productList = MS_ShoppingCartController.getProductDetails(product.Id);
        System.assertEquals(product.Name,productList[0].Name);
    }

    @IsTest
    public static void shouldConvertOrderItemToWrapperClass(){
        Order order = [SELECT Id FROM Order WHERE Name='Test Order'];
        List<OrderItem> orderItemsList = MS_ShoppingCartController.getOrderItems(order.Id);
        OrderItem item = [SELECT Id, Product2Id, Quantity, PricebookEntryId, UnitPrice FROM OrderItem];
        MS_ShoppingCartController.OrderItemWrapper wrapperObject = new MS_ShoppingCartController.OrderItemWrapper(item);
        MS_ShoppingCartController.parseWrapperToSObject(wrapperObject,order.Id);
        System.assertEquals(1000,wrapperObject.UnitPrice);
    }

    @IsTest
    public static void shouldCreateTwoTheSameWrappers(){
        Order order = [SELECT Id FROM Order WHERE Name='Test Order'];
        OrderItem item = [SELECT Id, Product2Id, Quantity, PricebookEntryId, UnitPrice FROM OrderItem];
        MS_ShoppingCartController.OrderItemWrapper wrapperObjectV1 = new MS_ShoppingCartController.OrderItemWrapper(item);
        MS_ShoppingCartController.OrderItemWrapper wrapperObjectV2 = new MS_ShoppingCartController.OrderItemWrapper(item.Product2Id,item.Quantity,item.PricebookEntryId,item.UnitPrice);
        System.assertEquals(wrapperObjectV1.product,wrapperObjectV2.product);
        System.assertEquals(wrapperObjectV1.quantity,wrapperObjectV2.quantity);
        System.assertEquals(wrapperObjectV1.pricebookEntry,wrapperObjectV2.pricebookEntry);
        System.assertEquals(wrapperObjectV1.UnitPrice ,wrapperObjectV2.UnitPrice);
    }

    @IsTest
    public static void shouldAddOneProductToCache(){
        Order order = [SELECT Id FROM Order WHERE Name='Test Order'];
        OrderItem item = [SELECT Id, Product2Id, Quantity, PricebookEntryId, UnitPrice FROM OrderItem];
        MS_ShoppingCartController.addProductToCacheShoppingCart(item.Product2Id, item.Quantity);
        MS_ShoppingCartController.addProductToCacheShoppingCart(item.Product2Id, 3);
        Integer numberOfProductInCache = MS_ShoppingCartController.getNumberOfProductInCache();
        System.assertEquals(1,numberOfProductInCache);
    }

    @IsTest
    public static void shouldAddOneAndDeleteOneProductFromCache(){
        Order order = [SELECT Id FROM Order WHERE Name='Test Order'];
        OrderItem item = [SELECT Id, Product2Id, Quantity, PricebookEntryId, UnitPrice FROM OrderItem];
        MS_ShoppingCartController.addProductToCacheShoppingCart(item.Product2Id, item.Quantity);
        MS_ShoppingCartController.updateQuantity(item.Product2Id, 3);
        MS_ShoppingCartController.deleteProductFromCache(item.Product2Id);
        MS_ShoppingCartController.deleteAllProductsFromCache();
        Integer numberOfProductInCache = MS_ShoppingCartController.getNumberItemsInCache();
        System.assertEquals(0,numberOfProductInCache);
    }

    @IsTest
    public static void shouldGetItemsFromCache(){
        Order order = [SELECT Id FROM Order WHERE Name='Test Order'];
        OrderItem item = [SELECT Id, Product2Id, Quantity, PricebookEntryId, UnitPrice FROM OrderItem];
        Id pricebookId = MS_ShoppingCartController.getPricebook();
        MS_ShoppingCartController.addProductToCacheShoppingCart(item.Product2Id, item.Quantity);
        List<MS_ShoppingCartController.OrderItemWrapper> wrapperList = MS_ShoppingCartController.getItemsFromCache();
        System.assertEquals(item.UnitPrice,wrapperList[0].UnitPrice);
    }

}