force-app/main/default/objects/Product2/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Producer__c.field-meta.xml
<CustomField>
    <fullName>Producer__c</fullName>
    <label>Producer</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>Intel</fullName>
            </value>
            <value>
                <fullName>Asus</fullName>
            </value>
            <value>
                <fullName>Acer</fullName>
            </value>
            <value>
                <fullName>Seagate</fullName>
            </value>
            <value>
                <fullName>Silentium</fullName>
            </value>
            <value>
                <fullName>Nvidia</fullName>
            </value>
            <value>
                <fullName>Sony</fullName>
            </value>
            <value>
                <fullName>HP</fullName>
            </value>
            <value>
                <fullName>A4Tech</fullName>
            </value>
            <value>
                <fullName>Adata</fullName>
            </value>
            <value>
                <fullName>Xiaomi</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>BenQ</fullName>
            </value>
            <value>
                <fullName>Dell</fullName>
            </value>
            <value>
                <fullName>MSI</fullName>
            </value>
            <value>
                <fullName>Biostar</fullName>
            </value>
            <value>
                <fullName>ASRock</fullName>
            </value>
            <value>
                <fullName>Philips</fullName>
            </value>
            <value>
                <fullName>Lenovo</fullName>
            </value>
            <value>
                <fullName>Cisco</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MS_FileControllerTest.cls
@IsTest
public with sharing class MS_FileControllerTest {
    @TestSetup
    public static void testSetup(){
        Product2 productTest = new Product2(Name='CPU i5',Model__c='i5-4434',Producer__c='Intel',ProductCode='G88E',Available__c=true,Family='CPU', DisplayUrl='Test');
        insert productTest;

        List<Product2> listProduct = [SELECT id FROM Product2 LIMIT 1];
        String tempPr;
        for(Product2 product : listProduct){
            tempPr = product.Id;
        }

        ContentVersion content=new ContentVersion(); 
        content.Title='Header_Picture1'; 
        content.FirstPublishLocationId = tempPr;
        content.PathOnClient='/' + content.Title + '.jpg'; 
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
        content.VersionData=bodyBlob; 
        insert content;
    }

    @IsTest
    public static void shouldReturnTrueDisplayUrl(){
        List<Product2> listProduct = [SELECT id FROM Product2 LIMIT 1];
        String tempPr;
        for(Product2 product : listProduct){
            tempPr = product.Id;
        }
        Boolean tempTest = MS_FileController.haveDisplayUrl(tempPr, 'Test');
        System.assertEquals(true, tempTest);
    }

    @IsTest
    public static void shouldReturnFalseDisplayUrl(){
        List<Product2> listProduct = [SELECT id FROM Product2 LIMIT 1];
        String tempPr;
        for(Product2 product : listProduct){
            tempPr = product.Id;
        }
        Boolean tempTest = MS_FileController.haveDisplayUrl(tempPr, 'yes');
        System.assertEquals(false, tempTest);
    }

    @IsTest
    public static void shouldReturnListVersionFilesDisplayUrl(){
        List<Product2> listProduct = [SELECT id FROM Product2 LIMIT 1];
        String tempPr;
        for(Product2 product : listProduct){
            tempPr = product.Id;
        }
        List <ContentVersion> tempList = MS_FileController.getVersionFiles(tempPr);
        System.assertEquals(1, tempList.size());

    }

    @IsTest
    public static void shouldNotReturnListVersionFilesDisplayUrl(){
        List <ContentVersion> tempList = MS_FileController.getVersionFiles('tempPr');
        System.assertEquals(0, tempList.size());
    }
}