force-app/main/default/objects/Product2/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Producer__c.field-meta.xml
<CustomField>
    <fullName>Producer__c</fullName>
    <label>Producer</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>Intel</fullName>
            </value>
            <value>
                <fullName>Asus</fullName>
            </value>
            <value>
                <fullName>Acer</fullName>
            </value>
            <value>
                <fullName>Seagate</fullName>
            </value>
            <value>
                <fullName>Silentium</fullName>
            </value>
            <value>
                <fullName>Nvidia</fullName>
            </value>
            <value>
                <fullName>Sony</fullName>
            </value>
            <value>
                <fullName>HP</fullName>
            </value>
            <value>
                <fullName>A4Tech</fullName>
            </value>
            <value>
                <fullName>Adata</fullName>
            </value>
            <value>
                <fullName>Xiaomi</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>BenQ</fullName>
            </value>
            <value>
                <fullName>Dell</fullName>
            </value>
            <value>
                <fullName>MSI</fullName>
            </value>
            <value>
                <fullName>Biostar</fullName>
            </value>
            <value>
                <fullName>ASRock</fullName>
            </value>
            <value>
                <fullName>Philips</fullName>
            </value>
            <value>
                <fullName>Lenovo</fullName>
            </value>
            <value>
                <fullName>Cisco</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MS_CustomSearchProduct.cls
public with sharing class MS_CustomSearchProduct {

    @AuraEnabled(cacheable = true)
    public static List<Product2> getProducts(String productName, String model, String productCode, String producer, String family){
        List<String> conditions = new List<String>();
        String query = 'SELECT Id, Name, Model__c, Producer__c, ProductCode, Available__c, Family FROM Product2 ';
        if (String.isNotBlank(productName)) {
            conditions.add('Name LIKE ' + '\'' + String.escapeSingleQuotes(productName) + '%\'');
        }
        if (String.isNotBlank(model)) {
            conditions.add('Model__c LIKE ' + '\'' + String.escapeSingleQuotes(model) + '%\'');
        }
        if (String.isNotBlank(productCode)) {
            conditions.add('ProductCode LIKE ' + '\'' + String.escapeSingleQuotes(productCode) + '%\'');
        }
        if (String.isNotBlank(producer) && producer != 'Other') {
            conditions.add('Producer__c LIKE ' + '\'' + String.escapeSingleQuotes(producer) + '%\'');
        }
        if (String.isNotBlank(family) && family != 'None') {
            conditions.add('Family LIKE ' + '\'' + String.escapeSingleQuotes(family) + '%\'');
        }

        if (conditions.size() > 0) {
            query += 'WHERE ' + conditions[0];
            for (Integer i = 1; i < conditions.size(); i++) {
                query += ' AND ' + conditions[i];
            }
        }
        return Database.query(query);
    }
}