force-app/main/default/objects/Product2/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Producer__c.field-meta.xml
<CustomField>
    <fullName>Producer__c</fullName>
    <label>Producer</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>Intel</fullName>
            </value>
            <value>
                <fullName>Asus</fullName>
            </value>
            <value>
                <fullName>Acer</fullName>
            </value>
            <value>
                <fullName>Seagate</fullName>
            </value>
            <value>
                <fullName>Silentium</fullName>
            </value>
            <value>
                <fullName>Nvidia</fullName>
            </value>
            <value>
                <fullName>Sony</fullName>
            </value>
            <value>
                <fullName>HP</fullName>
            </value>
            <value>
                <fullName>A4Tech</fullName>
            </value>
            <value>
                <fullName>Adata</fullName>
            </value>
            <value>
                <fullName>Xiaomi</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>BenQ</fullName>
            </value>
            <value>
                <fullName>Dell</fullName>
            </value>
            <value>
                <fullName>MSI</fullName>
            </value>
            <value>
                <fullName>Biostar</fullName>
            </value>
            <value>
                <fullName>ASRock</fullName>
            </value>
            <value>
                <fullName>Philips</fullName>
            </value>
            <value>
                <fullName>Lenovo</fullName>
            </value>
            <value>
                <fullName>Cisco</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductReview__c/ProductReview__c.object-meta.xml
<CustomObject>
    <label>ProductReview</label>
    <nameField>
        <label>ProductReview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductReviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductReview__c/fields/Accepted__c.field-meta.xml
<CustomField>
    <fullName>Accepted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accepted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProductReview__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>ProductReviews</relationshipLabel>
    <relationshipName>ProductReviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MS_CustomProductPageControllerTest.cls
@IsTest
public with sharing class MS_CustomProductPageControllerTest {

    @TestSetup
    public static void testSetup() {
        Pricebook2 standartPricebook = new Pricebook2(Id=Test.getStandardPricebookId(), IsActive=true);
        update  standartPricebook;
        Product2 productTest = new Product2(Name='CPU i5',Model__c='i5-4434',Producer__c='Intel',ProductCode='G88E',Family='CPU',IsActive=true);
        insert productTest;
        Product2 productTest2 = new Product2(Name='GPU RTX3060',Model__c='RTX',Producer__c='Nvidia',ProductCode='RTX3060',Family='GPU',IsActive=true);
        insert productTest2;
        PricebookEntry standartPrice = new PricebookEntry(UnitPrice=1000,Product2Id=productTest.Id, Pricebook2Id=standartPricebook.Id, IsActive=true);
        insert standartPrice;
        ProductReview__c reviewV1 = new ProductReview__c(Name='Test',Product__c=productTest.Id,Rating__c=4,Accepted__c=true);
        insert reviewV1;

        ContentVersion content=new ContentVersion(); 
        content.Title='Header_Picture1'; 
        content.FirstPublishLocationId = productTest.Id;
        content.PathOnClient='/' + content.Title + '.jpg'; 
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
        content.VersionData=bodyBlob; 
        insert content;
    }

    @IsTest
    public static void shouldReturnProductUnitPrice() {
        Product2 product = [SELECT Id FROM Product2 WHERE ProductCode='G88E'];
        List<PricebookEntry> productPrice = MS_CustomProductPageController.getProductPrice(product.Id);
        System.assertEquals(1000,productPrice[0].UnitPrice);
    }

    @IsTest
    public static void shouldReturnProductAllReviews() {
        Product2 product = [SELECT Id FROM Product2 WHERE ProductCode='G88E'];
        List<ProductReview__c> reviews = MS_CustomProductPageController.getAllReviews(product.Id);
        System.assertEquals(1,reviews.size());
    }

    @IsTest
    public static void shouldReturnProductOverallRating() {
        Product2 product = [SELECT Id FROM Product2 WHERE ProductCode='G88E'];
        List<AggregateResult> overallReviews = MS_CustomProductPageController.getProductOverallRating(product.Id);
        Decimal x = (Decimal) overallReviews[0].get('overallAverage');
        System.assertEquals(4,x);
    }

    @IsTest
    public static void shouldReturnOneContentProductLink() {
        Product2 product = [SELECT Id FROM Product2 WHERE ProductCode='G88E'];
        List<ContentDocumentLink> link = MS_CustomProductPageController.getProductImages(product.Id);
        System.assertEquals(1,link.size());
    }

    @IsTest
    public static void shouldReturnOneReviewProductExists() {
        Product2 product = [SELECT Id,CreatedBy.Id FROM Product2 WHERE ProductCode='G88E'];
        List<ProductReview__c> userReviewProductExist = MS_CustomProductPageController.checkUserHaveProductReview(product.CreatedBy.Id,product.Id);
        System.assertEquals(1,userReviewProductExist.size());
    }
}