force-app/main/default/objects/Product2/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Producer__c.field-meta.xml
<CustomField>
    <fullName>Producer__c</fullName>
    <label>Producer</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>Intel</fullName>
            </value>
            <value>
                <fullName>Asus</fullName>
            </value>
            <value>
                <fullName>Acer</fullName>
            </value>
            <value>
                <fullName>Seagate</fullName>
            </value>
            <value>
                <fullName>Silentium</fullName>
            </value>
            <value>
                <fullName>Nvidia</fullName>
            </value>
            <value>
                <fullName>Sony</fullName>
            </value>
            <value>
                <fullName>HP</fullName>
            </value>
            <value>
                <fullName>A4Tech</fullName>
            </value>
            <value>
                <fullName>Adata</fullName>
            </value>
            <value>
                <fullName>Xiaomi</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>BenQ</fullName>
            </value>
            <value>
                <fullName>Dell</fullName>
            </value>
            <value>
                <fullName>MSI</fullName>
            </value>
            <value>
                <fullName>Biostar</fullName>
            </value>
            <value>
                <fullName>ASRock</fullName>
            </value>
            <value>
                <fullName>Philips</fullName>
            </value>
            <value>
                <fullName>Lenovo</fullName>
            </value>
            <value>
                <fullName>Cisco</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MS_CustomSearchController.cls
public without sharing class MS_CustomSearchController {
    @AuraEnabled
        public static List<PricebookEntry> searchForIds(String searchText) {
          List<PricebookEntry> results = new List<PricebookEntry>();
          if(searchText.containsAny('%')){
            return results;
          }
          
          String inputSearch = '%'+searchText+'%';
          results = [SELECT Product2.Id, Product2.DisplayUrl, Product2.Family, Product2.Model__c, Product2.Name, Product2.Producer__c, UnitPrice FROM PricebookEntry WHERE Product2.isActive = true AND (
          Product2.Name LIKE :inputSearch OR 
          Product2.Model__c LIKE :inputSearch OR 
          Product2.Producer__c LIKE :inputSearch OR 
          Product2.Family LIKE :inputSearch)];
          return results;
    }


    private static List<Id> parseObjectToListId(List<PricebookEntry> pricebookEntry){
        List<Id> idList = new List<Id>();
        for(PricebookEntry temp : pricebookEntry){
          idList.add(temp.Product2.Id);
        }
        return idList;
    }

    @AuraEnabled
      public static List<PricebookEntry> searchProductsByFilters(String producer, String family, Integer minPrice, Integer maxPrice, List<PricebookEntry> ids){
        List<id> idList = parseObjectToListId(ids);
        List<String> conditions = new List<String>();
        String query = 'SELECT Product2.Id, Product2.DisplayUrl, Product2.Family, Product2.Model__c, Product2.Name, Product2.Producer__c, UnitPrice FROM PricebookEntry ';
        if (String.isNotBlank(producer) && producer != 'None') {
           conditions.add('Product2.Producer__c =  \'' + String.escapeSingleQuotes(producer) + '\'');
        }
        if (String.isNotBlank(family) && family != 'None') {
           conditions.add('Product2.Family =  \'' + String.escapeSingleQuotes(family) + '\'');
        }
           conditions.add(' (UnitPrice >= ' + minPrice + ' AND ' + ' UnitPrice <= ' + maxPrice);
      
        if (conditions.size() > 0) {
          query += ' WHERE ' + conditions[0];
          for (Integer i = 1; i < conditions.size(); i++) {
              query += ' AND ' + conditions[i];
          }
          query += ' AND Product2.Id IN :idList )';
        }
        return Database.query(query);
      }
}